version: '3'

services:

  app:
    build: .
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://docker:docker@database:5432/app?schema=public
    volumes:
      - .:/home/node/app

  database:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=app
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local